
server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cachestore
    username: root
    password: pass

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379